/**
 * SQL keywords for SQLite/D1 autocomplete
 * Organized by category for potential filtering/grouping
 */

/** SQL statement keywords */
export const SQL_STATEMENTS = [
  "SELECT",
  "INSERT",
  "UPDATE",
  "DELETE",
  "CREATE",
  "DROP",
  "ALTER",
  "REPLACE",
  "UPSERT",
] as const;

/** SQL clause keywords */
export const SQL_CLAUSES = [
  "FROM",
  "WHERE",
  "JOIN",
  "LEFT JOIN",
  "RIGHT JOIN",
  "INNER JOIN",
  "OUTER JOIN",
  "CROSS JOIN",
  "LEFT",
  "RIGHT",
  "INNER",
  "OUTER",
  "CROSS",
  "NATURAL",
  "ON",
  "USING",
  "AND",
  "OR",
  "NOT",
  "ORDER BY",
  "GROUP BY",
  "ORDER",
  "BY",
  "GROUP",
  "HAVING",
  "LIMIT",
  "OFFSET",
  "AS",
  "INTO",
  "VALUES",
  "SET",
  "UNION",
  "UNION ALL",
  "INTERSECT",
  "EXCEPT",
  "ALL",
  "CASE",
  "WHEN",
  "THEN",
  "ELSE",
  "END",
  "WITH",
  "RECURSIVE",
] as const;

/** SQL operator keywords */
export const SQL_OPERATORS = [
  "IN",
  "BETWEEN",
  "LIKE",
  "GLOB",
  "IS",
  "NULL",
  "EXISTS",
  "DISTINCT",
  "ASC",
  "DESC",
  "NULLS",
  "FIRST",
  "LAST",
  "ESCAPE",
  "COLLATE",
  "CAST",
] as const;

/** SQL aggregate and scalar functions */
export const SQL_FUNCTIONS = [
  // Aggregate functions
  "COUNT",
  "SUM",
  "AVG",
  "MAX",
  "MIN",
  "TOTAL",
  "GROUP_CONCAT",
  // Scalar functions
  "ABS",
  "COALESCE",
  "IFNULL",
  "IIF",
  "NULLIF",
  "LENGTH",
  "LOWER",
  "UPPER",
  "TRIM",
  "LTRIM",
  "RTRIM",
  "SUBSTR",
  "REPLACE",
  "INSTR",
  "PRINTF",
  "TYPEOF",
  "HEX",
  "QUOTE",
  "ZEROBLOB",
  "RANDOMBLOB",
  "UNICODE",
  "CHAR",
  // Date/time functions
  "DATE",
  "TIME",
  "DATETIME",
  "JULIANDAY",
  "STRFTIME",
  "CURRENT_DATE",
  "CURRENT_TIME",
  "CURRENT_TIMESTAMP",
  // Math functions (SQLite extension)
  "ROUND",
  "RANDOM",
  // JSON functions (D1 supported)
  "JSON",
  "JSON_ARRAY",
  "JSON_OBJECT",
  "JSON_EXTRACT",
  "JSON_INSERT",
  "JSON_REPLACE",
  "JSON_SET",
  "JSON_REMOVE",
  "JSON_TYPE",
  "JSON_VALID",
  "JSON_QUOTE",
  "JSON_GROUP_ARRAY",
  "JSON_GROUP_OBJECT",
  "JSON_EACH",
  "JSON_TREE",
] as const;

/** SQL data types */
export const SQL_TYPES = [
  "INTEGER",
  "TEXT",
  "REAL",
  "BLOB",
  "NUMERIC",
  "BOOLEAN",
  "VARCHAR",
  "CHAR",
  "DECIMAL",
  "FLOAT",
  "DOUBLE",
  "INT",
  "BIGINT",
  "SMALLINT",
  "TINYINT",
] as const;

/** SQL table/column definition keywords */
export const SQL_DEFINITIONS = [
  "TABLE",
  "INDEX",
  "VIEW",
  "TRIGGER",
  "COLUMN",
  "CONSTRAINT",
  "PRIMARY",
  "KEY",
  "FOREIGN",
  "REFERENCES",
  "UNIQUE",
  "CHECK",
  "DEFAULT",
  "AUTOINCREMENT",
  "ROWID",
  "WITHOUT",
  "STRICT",
  "IF",
  "EXISTS",
  "TEMPORARY",
  "TEMP",
  "VIRTUAL",
  "RENAME",
  "TO",
  "ADD",
  "CASCADE",
  "RESTRICT",
  "NO",
  "ACTION",
  "DEFERRABLE",
  "INITIALLY",
  "DEFERRED",
  "IMMEDIATE",
] as const;

/** D1/SQLite specific commands */
export const SQL_SQLITE_SPECIFIC = [
  "PRAGMA",
  "EXPLAIN",
  "QUERY",
  "PLAN",
  "VACUUM",
  "ANALYZE",
  "REINDEX",
  "ATTACH",
  "DETACH",
  "BEGIN",
  "COMMIT",
  "ROLLBACK",
  "SAVEPOINT",
  "RELEASE",
  "TRANSACTION",
] as const;

/** FTS5 specific keywords */
export const SQL_FTS5 = [
  "MATCH",
  "FTS5",
  "HIGHLIGHT",
  "SNIPPET",
  "BM25",
  "CONTENT",
  "CONTENTLESS",
  "TOKENIZE",
  "PREFIX",
  "PORTER",
  "ASCII",
  "UNICODE61",
] as const;

/** All SQL keywords combined (deduplicated) */
export const ALL_SQL_KEYWORDS: readonly string[] = [
  ...new Set([
    ...SQL_STATEMENTS,
    ...SQL_CLAUSES,
    ...SQL_OPERATORS,
    ...SQL_FUNCTIONS,
    ...SQL_TYPES,
    ...SQL_DEFINITIONS,
    ...SQL_SQLITE_SPECIFIC,
    ...SQL_FTS5,
  ]),
].sort();

/** Keywords that typically precede table names */
export const TABLE_CONTEXT_KEYWORDS = new Set([
  "FROM",
  "JOIN",
  "INTO",
  "UPDATE",
  "TABLE",
  "LEFT",
  "RIGHT",
  "INNER",
  "OUTER",
  "CROSS",
  "NATURAL",
]);

/** Keywords that typically precede column names */
export const COLUMN_CONTEXT_KEYWORDS = new Set([
  "SELECT",
  "WHERE",
  "AND",
  "OR",
  "ON",
  "SET",
  "ORDER",
  "GROUP",
  "BY",
  "HAVING",
  "WHEN",
  "THEN",
  "ELSE",
]);
